echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "I am learning branching in git and github"
echo "Proud of you batch33"
echo "Good luck For Practice"